# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
env:
  AZURE_RG: RG3
  AZURE_SUBSCRIPTION: f69ee048-384a-477f-8dc6-77bc118457cd
  AZURE-LOCATION: WestEurope
  AZURE-WEBAPP-NAME: dav-mywebapp
on:
  push:
    branches: [ "main" ]
    paths-ignore: ["README.md"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      configuration: release
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{env.configuration}}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{env.configuration}}
    - name: Publish
      run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp}}/publish
    - name: Upload the publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish_artifact
        path: ${{runner.temp}}/publish
        retention_days: 30
    - name: Upload a templates Artifact
      uses: actions/upload-artifact@v4
      with:
        name: templates_artifact
        path: ./templates/*
        retention-days: 30
  RG-Job:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Create Resource Group
        uses: Azure/cli@v2
        with:
          inlineScript:
            az group create --name ${{env.AZURE_RG}} --location ${{env.AZURE-LOCATION}}
  WebApp-Job:
    runs-on: ubuntu-latest
    needs: [RG-Job]
    steps:
      - name: Download Templates
        uses: actions/download-artifact@v4
        with:
          name: templates_artifact
          path: ${{ runner.temp }}/templates
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy BICEP template
        uses: azure/arm-deploy@v2
        id: deploywebapp
        with:
          deploymentName: create-webapp
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: ${{ runner.temp }}/templates/webapp.bicep
          parameters: location=${{ ENV.AZURE-LOCATION }} appName=${{ env.AZURE-WEBAPP-NAME }}
      - name: Download Publish
        uses: actions/download-artifact@v4
        with:
          name: publish_artifact
          path: ${{ runner.temp }}/publish
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.deploywebapp.outputs.webappname }}
          # app-name: ${{ env.AZURE-WEBAPP-NAME }}
          package: ${{ runner.temp }}/publish
